sudo: false
language: python

branches:
  only:
  - py35

notifications:
    email: false

python:
  - 3.5

before_install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install -r requirements.txt
  
install:
  - python setup.py install

script:
  - python -c 'import pybot'
