sudo: false
language: python
branches:
  only:
  - py35
notifications:
    email: false
python:
  # - "2.7"
  - "3.5"
  # - "3.6"
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda config --add channels anaconda
  - conda config --add channels menpo
  - conda config --show-sources
  - conda install -q pip requests conda-build anaconda-client
  - conda env create -f environment.yml -n test-environment
  - source activate test-environment
  - python setup.py install
  
  # - conda build conda-recipe # this assumes that the conda recipe folder is called conda-recipe and is at the current workind dir
  # - conda install --use-local $PACKAGENAME

  # Create test-environment with conda requirements

  # - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  # - conda env create -f environment.yml -n test-environment
  # - python setup.py build_ext --inplace

# script:
#   # Your test script goes here
# script: nosetests tests -A 'not slow and not random'

# after_success:
# # Change permissions for Anaconda deployment script
#   - chmod +x scripts/deploy_anaconda.sh

# deploy:
#  # Deploy to Anaconda.org
#   - provider: script
#     script: scripts/deploy_anaconda.sh
#     on:
#       tags: true
#     skip_cleanup: true
