package:
    name: pybot
    version: 0.1

source:
    git_url: https://github.com/spillai/pybot.git
    git_branch: py35
    
build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - python

    run:
        - numpy
        - python

about:
    home: http://spillai.github.io/pybot/
    license: MIT
