package:
    name: pybot
    version: 0.2

source:
    git_url: https://github.com/spillai/pybot.git
    git_branch: py35
  
build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - python
        - pip
        - numpy
        - six
        - wheel
    run:
        - numpy
        - python
        - pandas
    imports:
        - pybot

about:
    license: MIT
    summary: Research tools for autonomous systems using Python
